env = Environment()

env['APP_TARGET'] = 'ObjLoaderApp'
env['APP_SOURCES'] = ['ObjLoaderApp.cpp']
env['ASSETS'] = ['shader.frag', 'shader.vert']

SConscript('../../../../scons/SConscript', exports = 'env')
